Проектная работа 15
Mlenizyaka/Mesto_13_localhost2.github.io pull request #4
Opened 2020-04-05 21:59 UTC by Mlenizyaka

Добрый день!

В коде реализованы:
- все ошибки обрабатываются централизованно;
- запросы валидируются;
- ошибки и запросы логгируются в файлы error.log и request.log;
- файлы логов не добавляются в репозиторий;
- создан облачный сервер, API развернут;
- домен создан и прикреплен к серверу;
- к серверу можно обратиться по публичному IP-адресу, указанному в README.md;
- сертификаты выпущены и подключены;
- env переменные добавлены на сервер;
- сервер самостоятельно восстанавливается после GET-запроса на URL `/crash-test`;

2020-04-06 05:07 UTC, zhukovalexey76 requested changes
Требуются некоторые доработки

#### Надо исправить

1) Тут будет ошибка и сервер не запустится.

    ```javascript
    const { errorHandler } = require('../middlewares/errorHandler');
    ```

    ```text
    throw new TypeError('Router.use() requires a middleware function')
    ```

2) `Joi.string().required().url()`

    Кажется что нет такой ф-й. У меня возникает ошибка: 
    
    ```text
    TypeError: Joi.string(...).required(...).url is not a function
    ```
   
3) Не настроен HTTPS

4) На сервере указанном в README отсутствует `/crash-test`

5) Судя по всему на продакшене используется тот же ключ что и в DEV-режиме - `dev-secret`. С помощью этого ключа удаётся расшифровать токен генерируемый продакшеном.

2020-04-06 13:57 UTC, merged

2020-04-06 15:18 UTC, Mlenizyaka commented
Добрый день!

Я сразу прошу прощения, что раньше времени смерджила ветки, иначе не получалось залить обновления на сервер.

внесены необходимые корректировки:
- подключение мидлвары errorHandler исправлено;
- валидация celebrate исправлена;
- сертификаты ssl выпущены и подключены, https настроен;
- добавлен код для краш-теста;
- на сервер добавлен .env файл с ключом.

2020-04-07 14:02 UTC, zhukovalexey76 reviewed
Принято

#### Можно лучше

1) DeprecationWarning

    ```text
    DeprecationWarning: current Server Discovery and Monitoring
   engine is deprecated, and will be removed in a future version.
   To use the new Server Discover and Monitoring engine, pass option
   { useUnifiedTopology: true } to the MongoClient constructor.
    ```

    Такой вот ворнинг в консоли (терминале). Можно подумать над тем как от него избавиться.

2) У `ObjectID` есть метод `equals`. Так что вот такую штуку:

    `if (card.owner._id.toString() === req.user._id) {/*что-то там*/}`
    
    можно записать чуть более элегантно:
    
    `if (card.owner.equals(req.user._id)) {/*что-то там*/}`


3) Комментарий в controllers/users.js к [39й строке](https://github.com/Mlenizyaka/Mesto_13_localhost2.github.io/pull/4/files#diff-71dfd080cffe4efa09fc54e1b1b92ef4R39). Советую обратить на него внимание. Там есть ошибка. Если сделана случайно то ок, иначе с этой темой нужно разобраться, это важно. Еще посоветую неплохое [видео](https://www.youtube.com/watch?v=8cV4ZvHXQL4) по теме асинхронности в JS.

    И еще раз для закрепления:
    
    ```javascript
    new Promise(() => {}).then(() => {
      // код-1
    }).catch(() => {
       //...
    })
    // 1) Код на этой линии сработает раньше чем "код-1"
    // 2) Не нужно забывать про блок catch. Все ошибки должны обрабатываться.
    ```

2020-04-07 14:02 UTC, zhukovalexey76 commented on controllers/users.js
>    // хешируем пароль
Тут есть две проблемы. 1) User.findOne нужен блок catch. Он будет срабатывать когда напрмер ляжет база данных. 2) Вторая и самая главная - **bcrypt.hash не будет дожидаться пока выполнится User.findOne**. Всю эту штуку ниже нужно было положить в then от findOne или использовать синтаксис async/await чтобы не писать спагетти-код с коллбэками.

Пример с async/await:

```javascript
// Использовать await можно только внутри async-функций
const createUser = async (req, res, next) => {
  let user, hash;
  const { email, password } = req.body;

  try {
    user = await User.findOne({ email });
  } catch (err) {
    return next(err);
  }
  if (user) {
    return next(new BadRequestError('Такой пользователь уже существует'));
  }
  // Вот теперь можно обойтись без коллбеков
  try {
    hash = await bcrypt.hash(password, 10);
  } catch (err) {
    return next(err);
  }
  // User.create....
};
```

2020-04-07 14:02 UTC, zhukovalexey76 commented on routes/cards.js
> +    postId: Joi.string().alphanum().length(24),
тут просто id а не postId. Иначе валидация скажет что такое поле недопустимо.